server:
  port: 8082
  
spring:
  kafka:
    security:
      protocol: "SSL"
    bootstrap-servers: a2b0ba910d473425f9bff7f76b08084b-877566286.us-east-1.elb.amazonaws.com:9094
    ssl:
      trust-store-type: PEM
      trust-store-location: classpath:/client-certs/cluster-ca.crt
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer